use anyhow::{Context, Result};
use seccompiler::{
    apply_filter_all_threads, BpfProgram, SeccompAction, SeccompFilter, SeccompRule,
};
use std::collections::BTreeMap;

pub fn apply_seccomp_filter(dangerous: bool) -> Result<()> {
    if dangerous {
        return Ok(());
    }

    let mut rules: BTreeMap<i64, Vec<SeccompRule>> = BTreeMap::new();

    let allowed_syscalls = vec![
        libc::SYS_read,
        libc::SYS_write,
        libc::SYS_open,
        libc::SYS_close,
        libc::SYS_stat,
        libc::SYS_fstat,
        libc::SYS_lstat,
        libc::SYS_poll,
        libc::SYS_lseek,
        libc::SYS_mmap,
        libc::SYS_mprotect,
        libc::SYS_munmap,
        libc::SYS_brk,
        libc::SYS_rt_sigaction,
        libc::SYS_rt_sigprocmask,
        libc::SYS_rt_sigreturn,
        libc::SYS_ioctl,
        libc::SYS_pread64,
        libc::SYS_pwrite64,
        libc::SYS_readv,
        libc::SYS_writev,
        libc::SYS_access,
        libc::SYS_pipe,
        libc::SYS_select,
        libc::SYS_sched_yield,
        libc::SYS_mremap,
        libc::SYS_msync,
        libc::SYS_mincore,
        libc::SYS_madvise,
        libc::SYS_dup,
        libc::SYS_dup2,
        libc::SYS_nanosleep,
        libc::SYS_getpid,
        libc::SYS_socket,
        libc::SYS_connect,
        libc::SYS_accept,
        libc::SYS_sendto,
        libc::SYS_recvfrom,
        libc::SYS_sendmsg,
        libc::SYS_recvmsg,
        libc::SYS_shutdown,
        libc::SYS_bind,
        libc::SYS_listen,
        libc::SYS_getsockname,
        libc::SYS_getpeername,
        libc::SYS_socketpair,
        libc::SYS_setsockopt,
        libc::SYS_getsockopt,
        libc::SYS_clone,
        libc::SYS_fork,
        libc::SYS_vfork,
        libc::SYS_execve,
        libc::SYS_exit,
        libc::SYS_wait4,
        libc::SYS_kill,
        libc::SYS_uname,
        libc::SYS_fcntl,
        libc::SYS_flock,
        libc::SYS_fsync,
        libc::SYS_fdatasync,
        libc::SYS_truncate,
        libc::SYS_ftruncate,
        libc::SYS_getdents,
        libc::SYS_getcwd,
        libc::SYS_chdir,
        libc::SYS_fchdir,
        libc::SYS_rename,
        libc::SYS_mkdir,
        libc::SYS_rmdir,
        libc::SYS_creat,
        libc::SYS_link,
        libc::SYS_unlink,
        libc::SYS_symlink,
        libc::SYS_readlink,
        libc::SYS_chmod,
        libc::SYS_fchmod,
        libc::SYS_chown,
        libc::SYS_fchown,
        libc::SYS_lchown,
        libc::SYS_umask,
        libc::SYS_gettimeofday,
        libc::SYS_getrlimit,
        libc::SYS_getrusage,
        libc::SYS_sysinfo,
        libc::SYS_times,
        libc::SYS_getuid,
        libc::SYS_getgid,
        libc::SYS_setuid,
        libc::SYS_setgid,
        libc::SYS_geteuid,
        libc::SYS_getegid,
        libc::SYS_getppid,
        libc::SYS_getpgrp,
        libc::SYS_setsid,
        libc::SYS_setpgid,
        libc::SYS_getgroups,
        libc::SYS_setgroups,
        libc::SYS_setresuid,
        libc::SYS_getresuid,
        libc::SYS_setresgid,
        libc::SYS_getresgid,
        libc::SYS_getpgid,
        libc::SYS_setfsuid,
        libc::SYS_setfsgid,
        libc::SYS_getsid,
        libc::SYS_capget,
        libc::SYS_capset,
        libc::SYS_rt_sigpending,
        libc::SYS_rt_sigtimedwait,
        libc::SYS_rt_sigqueueinfo,
        libc::SYS_rt_sigsuspend,
        libc::SYS_sigaltstack,
        libc::SYS_personality,
        libc::SYS_statfs,
        libc::SYS_fstatfs,
        libc::SYS_getpriority,
        libc::SYS_setpriority,
        libc::SYS_sched_setparam,
        libc::SYS_sched_getparam,
        libc::SYS_sched_setscheduler,
        libc::SYS_sched_getscheduler,
        libc::SYS_sched_get_priority_max,
        libc::SYS_sched_get_priority_min,
        libc::SYS_sched_rr_get_interval,
        libc::SYS_mlock,
        libc::SYS_munlock,
        libc::SYS_mlockall,
        libc::SYS_munlockall,
        libc::SYS_prctl,
        libc::SYS_arch_prctl,
        libc::SYS_setrlimit,
        libc::SYS_sync,
        libc::SYS_gettid,
        libc::SYS_readahead,
        libc::SYS_setxattr,
        libc::SYS_lsetxattr,
        libc::SYS_fsetxattr,
        libc::SYS_getxattr,
        libc::SYS_lgetxattr,
        libc::SYS_fgetxattr,
        libc::SYS_listxattr,
        libc::SYS_llistxattr,
        libc::SYS_flistxattr,
        libc::SYS_removexattr,
        libc::SYS_lremovexattr,
        libc::SYS_fremovexattr,
        libc::SYS_tkill,
        libc::SYS_time,
        libc::SYS_futex,
        libc::SYS_sched_setaffinity,
        libc::SYS_sched_getaffinity,
        libc::SYS_set_thread_area,
        libc::SYS_io_setup,
        libc::SYS_io_destroy,
        libc::SYS_io_getevents,
        libc::SYS_io_submit,
        libc::SYS_io_cancel,
        libc::SYS_get_thread_area,
        libc::SYS_epoll_create,
        libc::SYS_getdents64,
        libc::SYS_set_tid_address,
        libc::SYS_restart_syscall,
        libc::SYS_semtimedop,
        libc::SYS_fadvise64,
        libc::SYS_timer_create,
        libc::SYS_timer_settime,
        libc::SYS_timer_gettime,
        libc::SYS_timer_getoverrun,
        libc::SYS_timer_delete,
        libc::SYS_clock_settime,
        libc::SYS_clock_gettime,
        libc::SYS_clock_getres,
        libc::SYS_clock_nanosleep,
        libc::SYS_exit_group,
        libc::SYS_epoll_wait,
        libc::SYS_epoll_ctl,
        libc::SYS_tgkill,
        libc::SYS_utimes,
        libc::SYS_mbind,
        libc::SYS_set_mempolicy,
        libc::SYS_get_mempolicy,
        libc::SYS_mq_open,
        libc::SYS_mq_unlink,
        libc::SYS_mq_timedsend,
        libc::SYS_mq_timedreceive,
        libc::SYS_mq_notify,
        libc::SYS_mq_getsetattr,
        libc::SYS_waitid,
        libc::SYS_ioprio_set,
        libc::SYS_ioprio_get,
        libc::SYS_inotify_init,
        libc::SYS_inotify_add_watch,
        libc::SYS_inotify_rm_watch,
        libc::SYS_migrate_pages,
        libc::SYS_openat,
        libc::SYS_mkdirat,
        libc::SYS_mknodat,
        libc::SYS_fchownat,
        libc::SYS_futimesat,
        libc::SYS_newfstatat,
        libc::SYS_unlinkat,
        libc::SYS_renameat,
        libc::SYS_linkat,
        libc::SYS_symlinkat,
        libc::SYS_readlinkat,
        libc::SYS_fchmodat,
        libc::SYS_faccessat,
        libc::SYS_pselect6,
        libc::SYS_ppoll,
        libc::SYS_set_robust_list,
        libc::SYS_get_robust_list,
        libc::SYS_splice,
        libc::SYS_tee,
        libc::SYS_sync_file_range,
        libc::SYS_vmsplice,
        libc::SYS_move_pages,
        libc::SYS_utimensat,
        libc::SYS_epoll_pwait,
        libc::SYS_signalfd,
        libc::SYS_timerfd_create,
        libc::SYS_eventfd,
        libc::SYS_fallocate,
        libc::SYS_timerfd_settime,
        libc::SYS_timerfd_gettime,
        libc::SYS_accept4,
        libc::SYS_signalfd4,
        libc::SYS_eventfd2,
        libc::SYS_epoll_create1,
        libc::SYS_dup3,
        libc::SYS_pipe2,
        libc::SYS_inotify_init1,
        libc::SYS_preadv,
        libc::SYS_pwritev,
        libc::SYS_rt_tgsigqueueinfo,
        libc::SYS_perf_event_open,
        libc::SYS_recvmmsg,
        libc::SYS_prlimit64,
        libc::SYS_name_to_handle_at,
        libc::SYS_open_by_handle_at,
        libc::SYS_syncfs,
        libc::SYS_sendmmsg,
        libc::SYS_getcpu,
        libc::SYS_process_vm_readv,
        libc::SYS_process_vm_writev,
        libc::SYS_sched_setattr,
        libc::SYS_sched_getattr,
        libc::SYS_renameat2,
        libc::SYS_seccomp,
        libc::SYS_getrandom,
        libc::SYS_memfd_create,
        libc::SYS_execveat,
        libc::SYS_membarrier,
        libc::SYS_mlock2,
        libc::SYS_copy_file_range,
        libc::SYS_preadv2,
        libc::SYS_pwritev2,
        libc::SYS_pkey_mprotect,
        libc::SYS_pkey_alloc,
        libc::SYS_pkey_free,
        libc::SYS_statx,
        libc::SYS_rseq,
    ];

    for syscall in allowed_syscalls {
        rules.insert(syscall, vec![]);
    }

    let filter = SeccompFilter::new(
        rules,
        SeccompAction::Trap,
        SeccompAction::Allow,
        std::env::consts::ARCH.try_into().unwrap(),
    )
    .context("failed to create seccomp filter")?;

    let program: BpfProgram = filter.try_into().context("failed to compile seccomp filter")?;

    apply_filter_all_threads(&program).context("failed to apply seccomp filter")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_seccomp_filter_creation() {
        let mut rules: BTreeMap<i64, Vec<SeccompRule>> = BTreeMap::new();
        rules.insert(libc::SYS_read, vec![]);
        rules.insert(libc::SYS_write, vec![]);

        let filter = SeccompFilter::new(
            rules,
            SeccompAction::Trap,
            SeccompAction::Allow,
            std::env::consts::ARCH.try_into().unwrap(),
        );

        assert!(filter.is_ok());
    }

    #[test]
    fn test_dangerous_mode_skips_filter() {
        let result = apply_seccomp_filter(true);
        assert!(result.is_ok());
    }
}
