name: ci

on:
  push:
  pull_request:

jobs:
  unprivileged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo fmt -- --check
      - run: cargo test --bin tinybox
      - run: cargo clippy -- -D warnings

  privileged-c0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
      - run: sudo ./scripts/test_c0.sh
      - run: sudo ./scripts/test_c1.sh
      - run: sudo ./scripts/test_c2.sh
      - run: sudo ./scripts/test_c3.sh
